spring.application.name=TicketingApp

#For Custom Banner
spring.banner.location=classpath:/com/application/TicketingApp/banner/banner.txt
spring.main.banner-mode=console

#/TicketingApp/src/main/java/com/application/TicketingApp/banner/banner.txt
server.servlet.context-path=/TicketingApp
#dev tools
spring.devtools.restart.enabled=true
# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/TicketingDB
# Database username
spring.datasource.username=root
# Database password
spring.datasource.password=rootpassword
# Show SQL statements
spring.jpa.show-sql=true
# Hibernate DDL auto
spring.jpa.hibernate.ddl-auto=update
#show sql
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
# Dialect for MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

logging.level.org.springframework.web=DEBUG

#Enabling Actuator endpoints
management.endpoints.web.exposure.include=*
# Excluding Actuator endpoints
management.endpoints.web.exposure.exclude=env,beans

#Swagger API
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
